// let d = new Date()
// console.log(d)
// //get method
// console.log(d.getDate())
// console.log(d.getMonth())
// console.log(d.getFullYear())
// console.log(d.getHours())
// console.log(d.getMinutes())
// console.log(d.getSeconds())
// console.log(d.getMilliseconds())
// console.log(d.getTime())
// console.log(getDay())
// console.log(Date.now())

// let d = new Date(2026,10,10,20,12,10)
// console.log(d)

const d = new Date()
d.setFullYear(2025)
d.setMonth(11)
d.setDate(21)
d.setHours(10)
d.setMinutes(10)
d.setSeconds(10)
d.setMilliseconds(1)
d.setTime(99000)
console.log(d)
// console.log(d.getTime())

